### ISSUE TITLE
The fan does not start.

### ISSUE THREAD

**Issue by pavluchenkor** [condottab/Roborock-CPAP#1]
For the test, I assembled the stm32 stand, the fan and the circuit that you kindly provided. Everything is connected to the power supply, common ground is everywhere, PWM is generated from minimum to maximum and back, the LED is connected in parallel to the fan input, and the PWM operation is clearly visible, i.e. the LED changes brightness, but the fan does not work. While the fan is connected to a power source, nothing happens, but it is only necessary to disconnect and connect the fan power, as it starts to work. I assume you are facing such a problem and that is why I am looking for a solution here. Tell me what can be done?

**Comment by ripinteer** [comment]
Looks like Nidec fan you have. They require to be powered from controllable hotend output, so the motherboard can handle the power set routine automatically. Check out the .cfg Nidec example in this repo

**Comment by pavluchenkor** [comment]
Thanks for the reply! That's right, it is Nidec, I forgot to report it. I looked at this example, everything is clear there, but I do not understand the nuances.
enable_pin: <hotend_output_grounded_pin> Should it be the hotend pin or any driven pin with high current?

**Comment by pavluchenkor** [comment]
And one more question. In case PWM for fan will be 0 klipper will turn off enable_fan_pin pin by itself, and when pwm will be more than 0 on enable_fan_pin there will be high level? Sorry, I'm not at all familiar with the inner workings of klipper and I'm concerned about the usual situation where I don't need fanning during printing for some reason and PWM = 0, but the next moment I need fanning. Do I understand the logic correctly, it is the klipper that controls enable_fan_pin itself based on the PWM value?

**Comment by pavluchenkor** [comment]
Please tell me, what should be the voltage of pwm, 5, 12 or 24V?
