### ISSUE TITLE
how to determine pwm out pin for mks boards?

### ISSUE THREAD

**Issue by selimayaz** [condottab/Roborock-CPAP#5]
Hello, thanks for useful project. I wonder which pin to use pwm out for MKS-Monster8. Thanks..

**Comment by condottab** [comment]
Not familiar with a board. Usually the neopixel/led pin works best because of the 5v pullup. If hw pwm doesn't work, try software pwm, this is a known problem for many boards.

**Comment by condottab** [comment]
Not familiar with a board. Usually the neopixel/led pin works best because of the 5v pullup. If hw pwm doesn't work, try software pwm, this is a known problem for many boards.
